[package]
name = "sibylline-clean-python"
version.workspace = true
edition.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
sibylline-clean = { path = "../sibylline-clean" }
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py310"] }
